name: Continous Integration and Deployment

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .Net 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build -c Release
        
  deploy-development:
    runs-on: windows-latest
    needs: build
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Debug GitHub Event
      run: echo "Inside If statement"
    - name: Deploy to Development
      run: dotnet publish -c Release -o .o/outDev

  deploy-production:
    runs-on: windows-latest
    needs: build
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Debug GitHub Event
      run: echo "Inside If statement"
    - name: Deploy to Production
      run: dotnet publish -c Release -o .o/outProd
